// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateChatData, CreateChatResponses, GetChatData, GetChatErrors, GetChatResponses, GetChatsData, GetChatsResponses, GetHealthData, GetHealthResponses, GetOpenapiJsonData, GetOpenapiJsonResponses, GetToolsData, GetToolsErrors, GetToolsResponses, ListOpenAiModelsData, ListOpenAiModelsErrors, ListOpenAiModelsResponses, OpenAiChatCompletionsData, OpenAiChatCompletionsErrors, OpenAiChatCompletionsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getOpenapiJson = <ThrowOnError extends boolean = false>(options?: Options<GetOpenapiJsonData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetOpenapiJsonResponses, unknown, ThrowOnError>({
        url: '/openapi.json',
        ...options
    });
};

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * Get all chats
 */
export const getChats = <ThrowOnError extends boolean = false>(options?: Options<GetChatsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetChatsResponses, unknown, ThrowOnError>({
        url: '/api/chats',
        ...options
    });
};

/**
 * Create a new chat session
 */
export const createChat = <ThrowOnError extends boolean = false>(options?: Options<CreateChatData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateChatResponses, unknown, ThrowOnError>({
        url: '/api/chats',
        ...options
    });
};

/**
 * Get chat by ID
 */
export const getChat = <ThrowOnError extends boolean = false>(options: Options<GetChatData, ThrowOnError>) => {
    return (options.client ?? client).get<GetChatResponses, GetChatErrors, ThrowOnError>({
        url: '/api/chats/{chatId}',
        ...options
    });
};

/**
 * Create a chat completion with OpenAI
 */
export const openAiChatCompletions = <ThrowOnError extends boolean = false>(options: Options<OpenAiChatCompletionsData, ThrowOnError>) => {
    return (options.client ?? client).post<OpenAiChatCompletionsResponses, OpenAiChatCompletionsErrors, ThrowOnError>({
        url: '/api/proxy/openai/chat/completions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List available models for OpenAI
 */
export const listOpenAiModels = <ThrowOnError extends boolean = false>(options: Options<ListOpenAiModelsData, ThrowOnError>) => {
    return (options.client ?? client).get<ListOpenAiModelsResponses, ListOpenAiModelsErrors, ThrowOnError>({
        url: '/api/proxy/openai/models',
        ...options
    });
};

/**
 * Get all tools
 */
export const getTools = <ThrowOnError extends boolean = false>(options?: Options<GetToolsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetToolsResponses, GetToolsErrors, ThrowOnError>({
        url: '/api/tools',
        ...options
    });
};
