// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:9000' | (string & {});
};

export type GetOpenapiJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.json';
};

export type GetOpenapiJsonResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetChatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chats';
};

export type GetChatsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        createdAt: string;
        updatedAt: string;
        interactions: Array<{
            id: string;
            chatId: string;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1186
             */
            content: {
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                role: 'developer';
                name?: string;
            } | {
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                role: 'system';
                name?: string;
            } | {
                content: string | Array<{
                    type: 'text';
                    text: string;
                } | {
                    type: 'image_url';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L765
                     */
                    image_url: {
                        url: string;
                        detail: 'auto' | 'low' | 'high';
                    };
                } | {
                    type: 'input_audio';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L792
                     */
                    input_audio: {
                        data: string;
                        format: 'wav' | 'mp3';
                    };
                } | {
                    type: 'file';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L732
                     */
                    file: {
                        file_data?: string;
                        file_id?: string;
                        filename?: string;
                    };
                }>;
                role: 'user';
                name?: string;
            } | {
                role: 'assistant';
                audio?: {
                    id: string;
                } | null;
                content?: string | Array<{
                    type: 'text';
                    text: string;
                }> | Array<{
                    type: 'refusal';
                    refusal: string;
                }> | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
                 */
                function_call?: {
                    arguments: string;
                    name: string;
                } | null;
                name?: string;
                refusal?: string | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
                 */
                tool_calls?: Array<{
                    id: string;
                    type: 'function';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                     */
                    function: {
                        arguments: string;
                        name: string;
                    };
                } | {
                    id: string;
                    type: 'custom';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                     */
                    custom: {
                        input: string;
                        name: string;
                    };
                }>;
            } | {
                role: 'tool';
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                tool_call_id: string;
            } | {
                role: 'function';
                content: string | null;
                name: string;
            };
            tainted: boolean;
            taintReason: string | null;
            createdAt: string;
        }>;
    }>;
};

export type GetChatsResponse = GetChatsResponses[keyof GetChatsResponses];

export type CreateChatData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chats';
};

export type CreateChatResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        createdAt: string;
        updatedAt: string;
    };
};

export type CreateChatResponse = CreateChatResponses[keyof CreateChatResponses];

export type GetChatData = {
    body?: never;
    path: {
        chatId: string;
    };
    query?: never;
    url: '/api/chats/{chatId}';
};

export type GetChatErrors = {
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetChatError = GetChatErrors[keyof GetChatErrors];

export type GetChatResponses = {
    /**
     * Default Response
     */
    200: {
        id: string;
        createdAt: string;
        updatedAt: string;
        interactions: Array<{
            id: string;
            chatId: string;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1186
             */
            content: {
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                role: 'developer';
                name?: string;
            } | {
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                role: 'system';
                name?: string;
            } | {
                content: string | Array<{
                    type: 'text';
                    text: string;
                } | {
                    type: 'image_url';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L765
                     */
                    image_url: {
                        url: string;
                        detail: 'auto' | 'low' | 'high';
                    };
                } | {
                    type: 'input_audio';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L792
                     */
                    input_audio: {
                        data: string;
                        format: 'wav' | 'mp3';
                    };
                } | {
                    type: 'file';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L732
                     */
                    file: {
                        file_data?: string;
                        file_id?: string;
                        filename?: string;
                    };
                }>;
                role: 'user';
                name?: string;
            } | {
                role: 'assistant';
                audio?: {
                    id: string;
                } | null;
                content?: string | Array<{
                    type: 'text';
                    text: string;
                }> | Array<{
                    type: 'refusal';
                    refusal: string;
                }> | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
                 */
                function_call?: {
                    arguments: string;
                    name: string;
                } | null;
                name?: string;
                refusal?: string | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
                 */
                tool_calls?: Array<{
                    id: string;
                    type: 'function';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                     */
                    function: {
                        arguments: string;
                        name: string;
                    };
                } | {
                    id: string;
                    type: 'custom';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                     */
                    custom: {
                        input: string;
                        name: string;
                    };
                }>;
            } | {
                role: 'tool';
                content: string | Array<{
                    type: 'text';
                    text: string;
                }>;
                tool_call_id: string;
            } | {
                role: 'function';
                content: string | null;
                name: string;
            };
            tainted: boolean;
            taintReason: string | null;
            createdAt: string;
        }>;
    };
};

export type GetChatResponse = GetChatResponses[keyof GetChatResponses];

export type OpenAiChatCompletionsData = {
    /**
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1487
     */
    body: {
        model: string;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1186
         */
        messages: Array<{
            content: string | Array<{
                type: 'text';
                text: string;
            }>;
            role: 'developer';
            name?: string;
        } | {
            content: string | Array<{
                type: 'text';
                text: string;
            }>;
            role: 'system';
            name?: string;
        } | {
            content: string | Array<{
                type: 'text';
                text: string;
            } | {
                type: 'image_url';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L765
                 */
                image_url: {
                    url: string;
                    detail: 'auto' | 'low' | 'high';
                };
            } | {
                type: 'input_audio';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L792
                 */
                input_audio: {
                    data: string;
                    format: 'wav' | 'mp3';
                };
            } | {
                type: 'file';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L732
                 */
                file: {
                    file_data?: string;
                    file_id?: string;
                    filename?: string;
                };
            }>;
            role: 'user';
            name?: string;
        } | {
            role: 'assistant';
            audio?: {
                id: string;
            } | null;
            content?: string | Array<{
                type: 'text';
                text: string;
            }> | Array<{
                type: 'refusal';
                refusal: string;
            }> | null;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
             */
            function_call?: {
                arguments: string;
                name: string;
            } | null;
            name?: string;
            refusal?: string | null;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
             */
            tool_calls?: Array<{
                id: string;
                type: 'function';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                 */
                function: {
                    arguments: string;
                    name: string;
                };
            } | {
                id: string;
                type: 'custom';
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                 */
                custom: {
                    input: string;
                    name: string;
                };
            }>;
        } | {
            role: 'tool';
            content: string | Array<{
                type: 'text';
                text: string;
            }>;
            tool_call_id: string;
        } | {
            role: 'function';
            content: string | null;
            name: string;
        }>;
        /**
         *
         * A function tool that can be used to generate a response.
         *
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1392
         *
         */
        tools?: Array<{
            type: 'function';
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
             */
            function: {
                name: string;
                description?: string;
                /**
                 * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                 */
                parameters?: {
                    [key: string]: unknown;
                };
                strict?: boolean | null;
            };
        } | {
            type: 'custom';
            custom: {
                /**
                 * The name of the custom tool, used to identify it in tool calls
                 */
                name: string;
                /**
                 * Optional description of the custom tool, used to provide more context
                 */
                description?: string;
                /**
                 * The input format for the custom tool. Default is unconstrained text.
                 */
                format?: {
                    /**
                     * Unconstrained text format. Always `text`
                     */
                    type: 'text';
                } | {
                    type: 'grammar';
                    /**
                     * Your chosen grammar
                     */
                    grammar: {
                        /**
                         * The grammar definition
                         */
                        definition: string;
                        /**
                         * The syntax of the grammar definition
                         */
                        syntax: 'lark' | 'regex';
                    };
                };
            };
        }>;
        /**
         * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1405
         */
        tool_choice?: 'none' | 'auto' | 'required' | {
            type: 'allowed_tools';
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1455
             */
            allowed_tools: {
                /**
                 *
                 * Constrains the tools available to the model to a pre-defined set.
                 *
                 * auto allows the model to pick from among the allowed tools and generate a
                 * message.
                 *
                 * required requires the model to call one or more of the allowed tools.
                 *
                 */
                mode: 'auto' | 'required';
                /**
                 * A list of tool definitions that the model should be allowed to call
                 */
                tools: Array<{
                    [key: string]: {
                        type: 'function';
                        /**
                         * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L174
                         */
                        function: {
                            name: string;
                            description?: string;
                            /**
                             * https://github.com/openai/openai-node/blob/master/src/resources/shared.ts#L217
                             */
                            parameters?: {
                                [key: string]: unknown;
                            };
                            strict?: boolean | null;
                        };
                    };
                }>;
            };
        } | {
            type: 'function';
            function: {
                name: string;
            };
        } | {
            type: 'custom';
            custom: {
                /**
                 * The name of the custom tool, used to identify it in tool calls
                 */
                name: string;
                /**
                 * Optional description of the custom tool, used to provide more context
                 */
                description?: string;
                /**
                 * The input format for the custom tool. Default is unconstrained text.
                 */
                format?: {
                    /**
                     * Unconstrained text format. Always `text`
                     */
                    type: 'text';
                } | {
                    type: 'grammar';
                    /**
                     * Your chosen grammar
                     */
                    grammar: {
                        /**
                         * The grammar definition
                         */
                        definition: string;
                        /**
                         * The syntax of the grammar definition
                         */
                        syntax: 'lark' | 'regex';
                    };
                };
            };
        };
        temperature?: number | null;
        max_tokens?: number | null;
        stream?: boolean | null;
    };
    headers: {
        'x-archestra-chat-id': string;
        /**
         * Bearer token for OpenAI
         */
        authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/proxy/openai/chat/completions';
};

export type OpenAiChatCompletionsErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    403: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    404: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type OpenAiChatCompletionsError = OpenAiChatCompletionsErrors[keyof OpenAiChatCompletionsErrors];

export type OpenAiChatCompletionsResponses = {
    /**
     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L248
     */
    200: {
        id: string;
        choices: Array<{
            finish_reason: 'stop' | 'length' | 'tool_calls' | 'content_filter' | 'function_call';
            index: number;
            logprobs: unknown;
            /**
             * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1000
             */
            message: {
                content: string | null;
                refusal: string | null;
                role: 'assistant';
                annotations?: Array<unknown>;
                audio?: unknown;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L431
                 */
                function_call?: {
                    arguments: string;
                    name: string;
                } | null;
                /**
                 * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1197
                 */
                tool_calls?: Array<{
                    id: string;
                    type: 'function';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1165
                     */
                    function: {
                        arguments: string;
                        name: string;
                    };
                } | {
                    id: string;
                    type: 'custom';
                    /**
                     * https://github.com/openai/openai-node/blob/v6.0.0/src/resources/chat/completions/completions.ts#L1128
                     */
                    custom: {
                        input: string;
                        name: string;
                    };
                }>;
            };
        }>;
        created: number;
        model: string;
        object: 'chat.completion';
        server_tier?: string;
        system_fingerprint?: string;
        /**
         * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L113
         */
        usage?: {
            completion_tokens: number;
            prompt_tokens: number;
            total_tokens: number;
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L144
             */
            completion_tokens_details?: unknown;
            /**
             * https://github.com/openai/openai-node/blob/master/src/resources/completions.ts#L173
             */
            prompt_tokens_details?: unknown;
        };
    };
};

export type OpenAiChatCompletionsResponse = OpenAiChatCompletionsResponses[keyof OpenAiChatCompletionsResponses];

export type ListOpenAiModelsData = {
    body?: never;
    headers: {
        /**
         * Bearer token for OpenAI
         */
        authorization: string;
    };
    path?: never;
    query?: never;
    url: '/api/proxy/openai/models';
};

export type ListOpenAiModelsErrors = {
    /**
     * Default Response
     */
    400: {
        error: string | {
            message: string;
            type: string;
        };
    };
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type ListOpenAiModelsError = ListOpenAiModelsErrors[keyof ListOpenAiModelsErrors];

export type ListOpenAiModelsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        /**
         * The model identifier, which can be referenced in the API endpoints
         */
        id: string;
        /**
         * The Unix timestamp (in seconds) when the model was created.
         */
        created: number;
        /**
         * The object type, which is always 'model'
         */
        object: 'model';
        /**
         * The organization that owns the model
         */
        owned_by: string;
    }>;
};

export type ListOpenAiModelsResponse = ListOpenAiModelsResponses[keyof ListOpenAiModelsResponses];

export type GetToolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tools';
};

export type GetToolsErrors = {
    /**
     * Default Response
     */
    500: {
        error: string | {
            message: string;
            type: string;
        };
    };
};

export type GetToolsError = GetToolsErrors[keyof GetToolsErrors];

export type GetToolsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        definition: string | number | boolean | null | {
            [key: string]: unknown;
        } | Array<unknown>;
        createdAt: string;
        updatedAt: string;
    }>;
};

export type GetToolsResponse = GetToolsResponses[keyof GetToolsResponses];
